### ISSUE TITLE
ReferenceError: window is not defined in node v12.10.0

### ISSUE THREAD

**Issue by jeetiss** [uploadcare/uploadcare-upload-client#68]
```
node --version
v12.10.0
```

```

/Users/jeetiss/Projects/uploadcare-upload-client/dist/uploadcare-upload-client.js:1557
    var browser = typeof self == 'object' ? self.FormData : window.FormData;
                                                            ^

ReferenceError: window is not defined
    at /Users/jeetiss/Projects/uploadcare-upload-client/dist/uploadcare-upload-client.js:1557:61
    at /Users/jeetiss/Projects/uploadcare-upload-client/dist/uploadcare-upload-client.js:9:68
    at Object.<anonymous> (/Users/jeetiss/Projects/uploadcare-upload-client/dist/uploadcare-upload-client.js:12:2)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)


```

**Comment by jeetiss** [comment]
uups
